version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: simon-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/simonmovilidad.db
    volumes:
      - sqlite_data:/app/data
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: simon-frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  sqlite_data:
